-- Generated by matugen — do not edit
-- Background / surface / foreground are locked to the Vicinae orchis-dark
-- palette. Only accent-family vars (primary/secondary/tertiary/error) shift
-- with the wallpaper.
return {
    primary             = "rgba({{colors.primary.default.hex_stripped}}ff)",
    on_primary          = "rgba({{colors.on_primary.default.hex_stripped}}ff)",
    primary_container   = "rgba({{colors.primary_container.default.hex_stripped}}ff)",
    secondary           = "rgba({{colors.secondary.default.hex_stripped}}ff)",
    tertiary            = "rgba({{colors.tertiary.default.hex_stripped}}ff)",
    error               = "rgba({{colors.error.default.hex_stripped}}ff)",
    -- Locked Vicinae orchis-dark base
    background          = "rgba(141414ff)",
    surface             = "rgba(1a1a1aff)",
    surface_container   = "rgba(2a2a2aff)",
    on_surface          = "rgba(fff3e0ff)",
    -- Subtle dark drop shadow (Vicinae/Raycast style), not a colored glow
    shadow              = "rgba(00000040)",
}
