-- Generated by matugen — do not edit
return {
    primary             = "rgba({{colors.primary.default.hex_stripped}}ff)",
    on_primary          = "rgba({{colors.on_primary.default.hex_stripped}}ff)",
    primary_container   = "rgba({{colors.primary_container.default.hex_stripped}}ff)",
    secondary           = "rgba({{colors.secondary.default.hex_stripped}}ff)",
    tertiary            = "rgba({{colors.tertiary.default.hex_stripped}}ff)",
    background          = "rgba({{colors.background.default.hex_stripped}}ff)",
    surface             = "rgba({{colors.surface.default.hex_stripped}}ff)",
    surface_container   = "rgba({{colors.surface_container.default.hex_stripped}}ff)",
    on_surface          = "rgba({{colors.on_surface.default.hex_stripped}}ff)",
    error               = "rgba({{colors.error.default.hex_stripped}}ff)",
    shadow              = "rgba({{colors.primary.default.hex_stripped}}cc)",
}
