# Fallback colors — overwritten by matugen on wallpaper change
$matugen_primary = rgba(ff9800ff)
$matugen_on_primary = rgba(000000ff)
$matugen_primary_container = rgba(ffcc80ff)
$matugen_secondary = rgba(ff8800ff)
$matugen_tertiary = rgba(ffab40ff)
$matugen_background = rgba(141414ff)
$matugen_surface = rgba(1a1a1aff)
$matugen_surface_container = rgba(2a2a2aff)
$matugen_on_surface = rgba(fff3e0ff)
$matugen_error = rgba(ff5722ff)
$matugen_shadow = rgba(ff9900cc)
