#!/usr/bin/env bash
# Switch between named Variety wallpaper theme profiles.
#
# Each theme is a Variety profile at ~/.config/variety-profiles/<theme>/
# with its own [sources] list. The current theme is persisted in
# $XDG_STATE_HOME/variety-theme so the login exec-once picks it up
# again on the next session.
#
# Usage:
#   variety-theme start           # launch variety with persisted theme
#   variety-theme next            # rotate to next theme and notify
#   variety-theme set <name>      # switch to specific theme
#   variety-theme current         # print current theme name

set -euo pipefail

STATE="${XDG_STATE_HOME:-$HOME/.local/state}/variety-theme"
THEMES=(landscapes space anime cyberpunk minimal)
KEYFILE="$HOME/.config/secrets/wallhaven_api_key"

current() {
    cat "$STATE" 2>/dev/null || echo "${THEMES[0]}"
}

# Splice the Wallhaven API key from the secrets cache into the active
# profile's variety.conf. The conf is regenerated by nix on every switch,
# so re-inject before each launch. Idempotent: strips existing key line first.
inject_wallhaven_key() {
    local conf="$1"
    [ -f "$conf" ] && [ -w "$conf" ] || return 0
    [ -r "$KEYFILE" ] || return 0
    local key
    key=$(cat "$KEYFILE")
    [ -n "$key" ] || return 0
    sed -i '/^wallhaven_api_key[[:space:]]*=/d' "$conf"
    printf '\nwallhaven_api_key = %s\n' "$key" >> "$conf"
}

start() {
    local theme="$1"
    mkdir -p "$(dirname "$STATE")"
    echo "$theme" >"$STATE"
    inject_wallhaven_key "$HOME/.config/variety-profiles/$theme/variety.conf"
    nohup variety --profile="$theme" >/dev/null 2>&1 &
    # Waybar's wallpaper module listens on SIGRTMIN+10 to refresh tooltip.
    pkill -SIGRTMIN+10 waybar 2>/dev/null || true
}

restart() {
    variety --quit 2>/dev/null || true
    sleep 0.3
    start "$1"
}

case "${1:-start}" in
start)
    start "$(current)"
    ;;
current)
    current
    ;;
set)
    if [ -z "${2:-}" ]; then
        echo "theme name required" >&2
        exit 1
    fi
    restart "$2"
    notify-send -a variety "Wallpaper" "Theme: $2"
    ;;
next)
    cur=$(current)
    idx=0
    for i in "${!THEMES[@]}"; do
        if [ "${THEMES[$i]}" = "$cur" ]; then
            idx=$i
            break
        fi
    done
    next_idx=$(((idx + 1) % ${#THEMES[@]}))
    next="${THEMES[$next_idx]}"
    restart "$next"
    notify-send -a variety "Wallpaper" "Theme: $next"
    ;;
*)
    echo "Usage: $0 {start|next|set <name>|current}" >&2
    exit 1
    ;;
esac
