[sources]
src1 = True|favorites|The Favorites folder
src2 = True|fetched|The Fetched folder
src3 = True|folder|~/.local/share/wallpapers
src4 = True|wallhaven|#minimalism;purity=100;categories=100;sorting=toplist;atleast=2560x1440;colors=000000,1a1a1a,333333
src5 = True|reddit|/r/minimalwallpaper
src6 = True|reddit|/r/DarkWallpapers
src7 = True|reddit|/r/Minimal
src8 = True|reddit|/r/wallpaper
